# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.2.0
  gcp-cli: circleci/gcp-cli@2.2.0
  slack: circleci/slack@4.4.2

jobs:
  build:
    steps:
      - maven/test:
        maven_command: ./mvnw
      - persist_to_workspace:
          root: workspace
          paths:
            - target
  deploy:
    steps:
      - attach_workspace:
          at: target
      - run: ls -la *

workflows:
  sample: 
    jobs:
      - build
      # TODO : Slack
      - deploy:
          requires:
            - build